version: "2"
otel-logs:
  source:
    otel_logs_source:
      ssl: false

  processor:
    - rename_keys:
        entries:
          - from_key: time
            to_key: timestamp
          - from_key: observedTime
            to_key: observedTimestamp

    - rename_keys:
        entries:
          - from_key: severityText
            to_key: severity/text
          - from_key: severityNumber
            to_key: severity/number

    - rename_keys:
        entries:
          - from_key: attributes/resource.attributes.service@name
            to_key: otel_attributes/service/name
          - from_key: attributes/resource.attributes.host@name
            to_key: otel_attributes/host/name
          - from_key: attributes/resource.attributes.k8s@namespace@name
            to_key: otel_attributes/k8s/namespace/name
          - from_key: attributes/resource.attributes.k8s@container@name
            to_key: otel_attributes/k8s/container/name
          - from_key: attributes/resource.attributes.k8s@pod@name
            to_key: otel_attributes/k8s/pod/name

    - rename_keys:
        entries:
          - from_key: attributes/log.attributes.service@name
            to_key: otel_attributes/service/name
            overwrite_if_to_key_exists: true
          - from_key: attributes/log.attributes.host@name
            to_key: otel_attributes/host/name
            overwrite_if_to_key_exists: true
          - from_key: attributes/log.attributes.http@method
            to_key: otel_attributes/http/method
            overwrite_if_to_key_exists: true
          - from_key: attributes/log.attributes.http@status_code
            to_key: otel_attributes/http/status_code
            overwrite_if_to_key_exists: true
          - from_key: attributes/log.attributes.http@target
            to_key: otel_attributes/http/target
            overwrite_if_to_key_exists: true
          - from_key: attributes/log.attributes.k8s@namespace@name
            to_key: otel_attributes/k8s/namespace/name
            overwrite_if_to_key_exists: true
          - from_key: attributes/log.attributes.k8s@container@name
            to_key: otel_attributes/k8s/container/name
            overwrite_if_to_key_exists: true
          - from_key: attributes/log.attributes.k8s@pod@name
            to_key: otel_attributes/k8s/pod/name
            overwrite_if_to_key_exists: true

  sink:
    - opensearch:
        hosts: [ "https://opensearch:9200" ]
        insecure: true
        username: admin
        password: admin
        index: ss4o_logs
        flush_timeout: -1
