version: "3.7"
services:
  data-prepper:
    restart: unless-stopped
    container_name: data-prepper
    image: opensearchproject/data-prepper:2
    volumes:
      - ./data-prepper/file-source.yaml:/usr/share/data-prepper/pipelines/file-source.yaml
      - ./input-files:/usr/share/data-prepper-input-files
      - ../../samples/certificates/data-prepper/server-cert.pem:/usr/share/data-prepper/config/server-cert.pem
      - ../../samples/certificates/data-prepper/private-key.pem:/usr/share/data-prepper/config/private-key.pem
    ports:
      - "2021:2021"
    networks:
      - sample_network

networks:
  sample_network: