ssl: true
keyStoreFilePath: "/usr/share/data-prepper/keystore.p12"
keyStorePassword: "password"
privateKeyPassword: "password"
serverPort: 4900
authentication:
  http_basic:
    username: admin
    password: admin

metricRegistries:
  - CloudWatch
