receivers:
  awsxray:
    transport: udp
    endpoint: 0.0.0.0:2000
    proxy_server:
      endpoint: 0.0.0.0:2000
      region: 'us-east-1'
      local_mode: true

exporters:
  awsxray:
    region: 'us-east-1'
  otlp/data-prepper:
    endpoint: data-prepper:21890
    tls:
      insecure: false
      ca_file: '/data-prepper-cert.pem'

service:
  pipelines:
    traces:
      receivers: [awsxray]
      exporters: [awsxray,otlp/data-prepper]
  telemetry:
    logs:
      level: 'debug'
