version: "3.7"
services:
  data-prepper:
    restart: unless-stopped
    container_name: data-prepper
    image: opensearchproject/data-prepper:2
    volumes:
      - ./data-prepper/pipelines:/usr/share/data-prepper/pipelines
      - ./data-prepper/log4j2-rolling.properties:/usr/share/data-prepper/config/log4j2-rolling.properties
      - ${HOME}/.aws:/root/.aws
    ports:
      - "4900:4900"
